#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <stdint.h>
#include <string.h>
#include <vector>
#include <map>
#include <limits.h>
#include <fstream>
#include <streambuf>
#include <sstream>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
//#define WIN32_LEAN_AND_MEAN
//#define NOMINMAX
//#include <Windows.h>
